plaga_site/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('', views.index, name = 'index'),
]

plaga_site/catalog/urls.py
from django.urls import path
from catalog import views

app_name = 'catalog'

urlpatterns = [
]

plaga_site/plaga_site/urls.py
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import include, path
from accounts import views as account_views
from catalog import views as cat_views
from . import views

#Add Django site authentication urls (for login, logout, password management)
urlpatterns = [
    path('polls/', include('polls.urls')),
    path('accounts/', include('accounts.urls')),
    # path('', include('templates/admin/base_site.html')),
    path('', views.IndexView.as_view(), name='index'),
    # # path('', views.HomePage.as_view(), name="home"),
    # path('accounts_app/', include('accounts.urls')),
    # path('', RedirectView.as_view(url='/admin/base_site.html')),
    # path('catalog/', include('catalog.urls')),
    # # path('', RedirectView.as_view(url='/catalog/')),
    path('admin/', admin.site.urls),
    # path(r"^accounts/", include("django.contrib.auth.urls")),
    # path(r"^accounts/", include("accounts.urls", namespace="accounts")),
]

plaga_site/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/',views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/',views.vote, name='vote'),
]

plaga_site/accounts/models.py
from django.db import models

# Create your models here.
# class AccountModel(models.Model):

plaga_site/catalog/models.py
from django.db import models

# Create your models here.

plaga_site/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
# extra info https://docs.djangoproject.com/en/2.0/intro/tutorial02/

class Question(models.Model):

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

plaga_site/accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return HttpResponse("Hello, world. You're at the accounts index.")

plaga_site/catalog/views.py
from django.shortcuts import render

# Create your views here.

plaga_site/plaga_site/views.py
from django.http import HttpResponseRedirect
from django.views import generic
#
# class PlagaSiteHomeView(generic.TemplateView):
#     template_name = 'base_site.html'
class IndexView(generic.TemplateView):
    template_name = 'index.html'
    # context_object_name = 'latest_question_list'
    #
    # def get_queryset(self):
    #
    #     return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

plaga_site/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question

'''
    Each view is responsible for doing one of two things:
        returning and HttpResponse object containing the content for
        the requested page, or raising an exception such as Http404.
        The rest is up to you

        https://docs.djangoproject.com/en/2.0/intro/tutorial04/
'''

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):

        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
        model = Question
        template_name = 'polls/detail.html'

        def get_queryset(self):
            return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting formself.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
                # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

plaga_site/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="POST">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{choice.choice_text }}</label>
    <br />
  {% endfor %}
  <input type="submit"value="Vote">

</form>

plaga_site/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />


{% if latest_question_list %}

  <ul>
    {% for question in latest_question_list %}
      <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>No polls are available.</p>
{% endif %}

plaga_site/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice.set.all %}
  <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

plaga_site/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en" dir="ltr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Plaga Home</title>
  </head>
  <body>
<!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>


    <div class="container my_content">
      {% block content %}

      {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>

plaga_site/templates/index.html
{% extends "base.html" %}
{% block content %}

  <h1>Welcome to Plaga</h1>
  <h2>An indie metroidvania game.</h2>

{% endblock %}

plaga_site/templates/test.html
{% extends "base.html" %}

{% block content %}
  <h1>Welcome to test.html!</h1>
{% endblock %}

plaga_site/templates/thanks.html
{% extends "base.html" %}

{% block content %}

  <h1>Welcome to the thanks.html!</h1>
  
{% endblock %}